<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Amoo Tobi Michael | Executive Virtual Assistant</title>
<meta name="description" content="Amoo Tobi Michael — Executive Virtual Assistant portfolio showcasing administrative support, AI-assisted productivity, workflow organization, CRM support and digital tools.">
<style>
:root{--ink:#111827;--muted:#667085;--paper:#f7f8fb;--white:#fff;--accent:#4f46e5;--accent2:#7c3aed;--line:#e6e8ef;--dark:#0b1020;--soft:#eef2ff}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:var(--ink);background:var(--paper);line-height:1.65}.container{max-width:1160px;margin:auto;padding:0 24px}
.nav{position:sticky;top:0;z-index:20;background:rgba(255,255,255,.9);backdrop-filter:blur(14px);border-bottom:1px solid var(--line)}.navin{height:72px;display:flex;align-items:center;justify-content:space-between}.brand{font-weight:850;letter-spacing:-.3px}.brand span{color:var(--accent)}.navlinks a{margin-left:22px;text-decoration:none;color:var(--ink);font-size:14px;font-weight:650}
.hero{padding:90px 0 78px;background:radial-gradient(circle at 85% 20%,#e9e7ff 0,transparent 30%),linear-gradient(135deg,#fff 0,#f4f3ff 100%)}.hero-grid{display:grid;grid-template-columns:1.25fr .75fr;gap:64px;align-items:center}.kicker,.eyebrow{display:inline-block;text-transform:uppercase;letter-spacing:1.7px;font-weight:850;font-size:12px;color:var(--accent)}h1{font-size:clamp(44px,6vw,72px);line-height:1.02;letter-spacing:-2.8px;margin:15px 0 20px}.lead{font-size:19px;color:var(--muted);max-width:720px}.btn{display:inline-block;padding:13px 18px;border-radius:11px;text-decoration:none;font-weight:750;margin:12px 10px 0 0}.primary{background:var(--ink);color:#fff}.secondary{background:#fff;color:var(--ink);border:1px solid var(--line)}
.profile{position:relative}.profile img{width:100%;max-width:390px;aspect-ratio:4/5;object-fit:cover;object-position:center 18%;display:block;margin:auto;border-radius:28px;box-shadow:0 28px 70px rgba(16,24,40,.18)}.profile-badge{position:absolute;right:0;bottom:28px;background:#fff;border:1px solid var(--line);padding:13px 16px;border-radius:15px;box-shadow:0 12px 35px rgba(16,24,40,.12);font-size:13px;font-weight:800}
section{padding:78px 0}.section-head{max-width:740px;margin-bottom:32px}h2{font-size:36px;letter-spacing:-1.2px;line-height:1.15;margin:8px 0 12px}.sub{color:var(--muted);margin:0}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.card{background:var(--white);border:1px solid var(--line);border-radius:18px;padding:25px;box-shadow:0 8px 30px rgba(16,24,40,.045)}.card h3{margin:0 0 8px;font-size:18px}.muted{color:var(--muted)}
.services .card{min-height:190px}.icon{width:42px;height:42px;border-radius:12px;background:var(--soft);display:grid;place-items:center;color:var(--accent);font-weight:900;margin-bottom:18px}.tagrow{display:flex;flex-wrap:wrap;gap:9px;margin-top:18px}.tag{font-size:12px;font-weight:700;padding:7px 10px;background:#f3f4f6;border:1px solid var(--line);border-radius:999px}
.evidence{background:#fff}.evidence-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:20px}.evidence-card{overflow:hidden;background:#fff;border:1px solid var(--line);border-radius:20px}.evidence-visual{height:300px;background:linear-gradient(135deg,#eef2ff,#f8fafc);display:grid;place-items:center;padding:25px}.mock{width:100%;height:100%;border:1px solid #d9deea;border-radius:13px;background:#fff;box-shadow:0 10px 28px rgba(16,24,40,.08);padding:16px}.mockbar{height:10px;width:42%;background:#dfe3eb;border-radius:99px;margin-bottom:18px}.mockline{height:9px;background:#edf0f5;border-radius:99px;margin:9px 0}.mockline.short{width:58%}.mockchips{display:flex;gap:7px;margin-top:16px}.mockchip{height:25px;width:74px;border-radius:7px;background:#eef2ff}.evidence-copy{padding:22px}.proof-image{width:100%;height:100%;object-fit:cover;border-radius:13px;display:block}.proof-image.contain{object-fit:contain;background:#fff}.proof-link{display:block;height:100%;cursor:zoom-in}.proof-label{display:inline-flex;align-items:center;gap:7px;margin-top:14px;font-size:11px;font-weight:800;color:var(--muted)}.stage{font-size:11px;text-transform:uppercase;letter-spacing:1.2px;color:var(--accent);font-weight:850}.evidence-copy h3{margin:7px 0}.proof-note{margin-top:14px;padding:10px 12px;border-radius:10px;background:#fafafa;border:1px dashed #cfd4df;font-size:12px;color:var(--muted)}
.process{counter-reset:steps}.process .card{display:flex;gap:16px;align-items:flex-start}.num{min-width:40px;height:40px;border-radius:50%;background:var(--ink);color:#fff;display:grid;place-items:center;font-weight:850}.case{display:grid;grid-template-columns:1fr 1fr;gap:20px}.case .card{min-height:250px}.case ul{padding-left:18px;color:var(--muted)}
.tools{display:flex;flex-wrap:wrap;gap:10px}.tool{padding:10px 13px;background:#fff;border:1px solid var(--line);border-radius:10px;font-weight:700;font-size:13px}.cert{display:grid;grid-template-columns:1fr .7fr;gap:22px;align-items:center}.cert-placeholder{min-height:220px;border:1px dashed #c8ceda;border-radius:18px;display:grid;place-items:center;background:#fafbfc;color:var(--muted);text-align:center;padding:20px}
.contact{background:var(--dark);color:#fff}.contact .muted{color:#b8c0d2}.contact a{color:#fff}.contactbox{display:flex;justify-content:space-between;gap:30px;align-items:end}.footer{padding:25px 0;text-align:center;color:var(--muted);font-size:13px}
.contact .cta{display:inline-flex;align-items:center;gap:9px;margin-top:18px;padding:14px 20px;border-radius:11px;text-decoration:none;font-weight:750;background:linear-gradient(135deg,var(--accent),var(--accent2));color:#fff!important;box-shadow:0 10px 26px rgba(124,58,237,.35);transition:transform .15s ease,box-shadow .15s ease}.contact .cta:hover{transform:translateY(-2px);box-shadow:0 14px 32px rgba(124,58,237,.45)}.contact .cta svg{flex-shrink:0}
@media(max-width:820px){.hero-grid,.case,.cert{grid-template-columns:1fr}.profile{order:-1}.profile img{max-width:300px}.grid,.evidence-grid{grid-template-columns:1fr}.navlinks{display:none}.hero{padding-top:55px}h1{letter-spacing:-1.8px}.contactbox{display:block}}
</style>
</head>
<body>
<nav class="nav"><div class="container navin"><div class="brand">Amoo Tobi <span>Michael</span></div><div class="navlinks"><a href="#about">About</a><a href="#services">Services</a><a href="#evidence">Proof</a><a href="#tools">Tools</a><a href="#contact">Contact</a></div></div></nav>

<header class="hero"><div class="container hero-grid"><div>
<div class="kicker">Executive Virtual Assistant</div>
<h1>Reliable support for executives who value clarity, time and follow-through.</h1>
<p class="lead">I’m Amoo Tobi Michael. I support executives and growing teams with organized administration, calendar and inbox coordination, customer support, data management, AI-assisted productivity and practical workflow systems.</p>
<a class="btn primary" href="#evidence">View My Work</a><a class="btn secondary" href="mailto:Michaelamoo.ma@gmail.com">Contact Me</a>
<div class="tagrow"><span class="tag">Remote Ready</span><span class="tag">Detail-Oriented</span><span class="tag">AI-Assisted</span><span class="tag">Process-Focused</span></div>
</div><div class="profile"><img src="assets/profile.jpg" alt="Professional portrait of Amoo Tobi Michael"><div class="profile-badge">Available for VA Opportunities</div></div></div></header>

<section id="about"><div class="container"><div class="section-head"><div class="eyebrow">About Me</div><h2>Organized support that keeps important work moving.</h2><p class="sub">My approach is simple: understand the priority, organize the workflow, execute accurately and communicate clearly.</p></div><div class="grid"><div class="card"><h3>Executive Support</h3><p class="muted">Calendar coordination, meeting preparation, follow-ups, document support and day-to-day administrative assistance.</p></div><div class="card"><h3>Digital Organization</h3><p class="muted">Structured files, task systems, spreadsheets and dashboards that make information easier to find and act on.</p></div><div class="card"><h3>AI & Automation</h3><p class="muted">Practical use of AI and automation tools to reduce repetitive work and improve turnaround time.</p></div></div></div></section>

<section id="services" class="services"><div class="container"><div class="section-head"><div class="eyebrow">Services</div><h2>How I can support your operation</h2></div><div class="grid">
<div class="card"><div class="icon">01</div><h3>Calendar Management</h3><p class="muted">Scheduling, rescheduling, reminders, priority blocks, meeting buffers and follow-up coordination.</p></div>
<div class="card"><div class="icon">02</div><h3>Inbox Management</h3><p class="muted">Email organization, prioritization, response drafting, action tracking and follow-up management.</p></div>
<div class="card"><div class="icon">03</div><h3>Research & Administrative Support</h3><p class="muted">Online research, document preparation, information organization, data entry and recurring administrative workflows.</p></div>
<div class="card"><div class="icon">04</div><h3>CRM & Customer Support</h3><p class="muted">Customer records, ticket updates, professional responses and structured issue follow-up.</p></div>
<div class="card"><div class="icon">05</div><h3>Notion & Workflow Systems</h3><p class="muted">Task dashboards, databases, trackers and simple systems for visibility and accountability.</p></div>
<div class="card"><div class="icon">06</div><h3>AI-Assisted Productivity</h3><p class="muted">AI-supported research, drafting, summarization, organization and workflow improvement using modern tools.</p></div>
<div class="card"><div class="icon">07</div><h3>Excel Data Entry & Reporting</h3><p class="muted">Structured data entry, spreadsheet organization, schedule preparation, formatting and information accuracy.</p></div>
</div></div></section>

<section id="evidence" class="evidence"><div class="container"><div class="section-head"><div class="eyebrow">Proof of Work</div><h2>Visual evidence, organized by workflow stage.</h2><p class="sub">Selected real-work screenshots are shown below as visual evidence of my workflow. More proof can be added as projects are completed.</p></div>
<div class="evidence-grid">
<div class="evidence-card"><div class="evidence-visual"><a class="proof-link" href="assets/proof/calendar-management.jpg" target="_blank" rel="noopener"><img class="proof-image" src="assets/proof/calendar-management.jpg" alt="Google Calendar weekly schedule showing organized meetings, priorities and time blocks"></a></div><div class="evidence-copy"><div class="stage">Featured Proof · Calendar</div><h3>Plan → Schedule → Coordinate</h3><p class="muted">A real Google Calendar workflow demonstrating meeting coordination, time blocking, priorities and structured scheduling.</p><div class="proof-label">✓ Real workflow screenshot · Click image to view</div></div></div>
<div class="evidence-card"><div class="evidence-visual"><a class="proof-link" href="assets/proof/email-management.jpg" target="_blank" rel="noopener"><img class="proof-image" src="assets/proof/email-management.jpg" alt="Gmail inbox showing organized email communication and executive assistant application correspondence"></a></div><div class="evidence-copy"><div class="stage">Featured Proof · Email</div><h3>Review → Prioritize → Respond</h3><p class="muted">A real Gmail inbox demonstrating email monitoring, message prioritization and professional communication workflow.</p><div class="proof-label">✓ Real workflow screenshot · Click image to view</div></div></div>
<div class="evidence-card"><div class="evidence-visual"><a class="proof-link" href="assets/proof/research-document-support.jpg" target="_blank" rel="noopener"><img class="proof-image contain" src="assets/proof/research-document-support.jpg" alt="Research and administrative document workflow displayed in Google Docs"></a></div><div class="evidence-copy"><div class="stage">Featured Proof · Research</div><h3>Research → Review → Document</h3><p class="muted">A real document-support example showing research, information organization and professional document preparation.</p><div class="proof-label">✓ Real workflow screenshot · Click image to view</div></div></div>
<div class="evidence-card"><div class="evidence-visual"><a class="proof-link" href="assets/proof/zapier-workflow-automation.jpg" target="_blank" rel="noopener"><img class="proof-image" src="assets/proof/zapier-workflow-automation.jpg" alt="Zapier Tables and Copilot automation collecting client information from Google Forms into a structured table"></a></div><div class="evidence-copy"><div class="stage">Featured Proof · Zapier Automation</div><h3>Design → Automate → Structure</h3><p class="muted">A real Zapier workflow using Tables and Copilot to automatically collect client intake information from Google Forms into an organized, ready-to-use database.</p><div class="proof-label">✓ Real workflow screenshot · Click image to view</div></div></div>
<div class="evidence-card"><div class="evidence-visual"><a class="proof-link" href="assets/proof/chatgpt-ai-workflow.jpg" target="_blank" rel="noopener"><img class="proof-image" src="assets/proof/chatgpt-ai-workflow.jpg" alt="ChatGPT conversation preparing interview talking points and guidance for a virtual assistant role"></a></div><div class="evidence-copy"><div class="stage">Featured Proof · ChatGPT Workflow</div><h3>Ask → Draft → Refine</h3><p class="muted">A real ChatGPT session used to prepare structured, professional interview talking points and response strategy — part of my AI-assisted research and drafting process.</p><div class="proof-label">✓ Real workflow screenshot · Click image to view</div></div></div>
<div class="evidence-card"><div class="evidence-visual"><a class="proof-link" href="assets/proof/excel-data-entry-reporting.jpg" target="_blank" rel="noopener"><img class="proof-image" src="assets/proof/excel-data-entry-reporting.jpg" alt="Excel spreadsheet showing structured schedule data entry and formatting"></a></div><div class="evidence-copy"><div class="stage">Featured Proof · Excel</div><h3>Enter → Structure → Format</h3><p class="muted">A real Excel workflow showing structured data entry, spreadsheet organization and professional formatting for a passenger schedule.</p><div class="proof-label">✓ Real workflow screenshot · Sensitive names redacted · Click image to view</div></div></div>
</div></div></section>

<section><div class="container"><div class="section-head"><div class="eyebrow">My Process</div><h2>A clear four-step working method</h2></div><div class="grid process">
<div class="card"><div class="num">1</div><div><h3>Understand</h3><p class="muted">Clarify the goal, priority, deadline, constraints and expected outcome.</p></div></div>
<div class="card"><div class="num">2</div><div><h3>Organize</h3><p class="muted">Turn information and requests into a structured, trackable workflow.</p></div></div>
<div class="card"><div class="num">3</div><div><h3>Execute</h3><p class="muted">Complete the work accurately and keep stakeholders informed.</p></div></div>
<div class="card"><div class="num">4</div><div><h3>Improve</h3><p class="muted">Identify repeatable tasks that can be simplified, documented or automated.</p></div></div>
</div></div></section>

<section id="tools"><div class="container"><div class="section-head"><div class="eyebrow">Tools & Skills</div><h2>My digital toolkit</h2></div><div class="tools"><span class="tool">Google Workspace</span><span class="tool">Microsoft Office</span><span class="tool">Google Calendar</span><span class="tool">Gmail</span><span class="tool">Notion</span><span class="tool">Zapier</span><span class="tool">Claude AI</span><span class="tool">Claude Code</span><span class="tool">ChatGPT</span><span class="tool">CRM Systems</span><span class="tool">Data Entry</span><span class="tool">Customer Support</span><span class="tool">Online Research</span><span class="tool">Document Management</span><span class="tool">Workflow Organization</span></div></div></section>

<section><div class="container"><div class="section-head"><div class="eyebrow">Certification</div><h2>Professional Development</h2></div><div class="cert"><div class="card"><h3>Virtual Assistant Professional Skills</h3><p class="muted">Alison · 12 August 2026</p><p>This certificate documents my completion of Virtual Assistant Professional Skills training.</p><p><strong>Certificate holder:</strong> Amoo Tobi Michael</p><a class="btn primary" href="assets/cert/ATM-Virtual-Assistant-Certification.pdf" target="_blank" rel="noopener">View Certificate PDF</a></div><div class="cert-placeholder" style="padding:12px"><a class="proof-link" href="assets/cert/ATM-Virtual-Assistant-Certification.pdf" target="_blank" rel="noopener"><img class="proof-image contain" src="assets/cert/certificate.png" alt="Amoo Tobi Michael Virtual Assistant Professional Skills certificate from Alison"></a></div></div></div></section>

<section id="contact" class="contact"><div class="container contactbox"><div><div class="eyebrow">Let’s Work Together</div><h2>Need dependable executive support?</h2><p class="muted">Available for remote Executive Virtual Assistant, administrative, customer support, data and workflow projects.</p></div><div><p><strong>Email:</strong> <a href="mailto:Michaelamoo.ma@gmail.com">Michaelamoo.ma@gmail.com</a><br><strong>Phone:</strong> 08093814709<br><strong>LinkedIn:</strong> <a href="https://www.linkedin.com/in/michael-amoo-434b22163" target="_blank" rel="noopener">linkedin.com/in/michael-amoo-434b22163</a></p><a class="cta" href="mailto:Michaelamoo.ma@gmail.com"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M22 2L11 13" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><path d="M22 2L15 22L11 13L2 9L22 2Z" stroke="white" stroke-width="2" stroke-linejoin="round"/></svg>Start a Conversation</a></div></div></section>
<footer class="footer">© 2026 Amoo Tobi Michael · Executive Virtual Assistant</footer>
</body></html>
